print("======================================")
print("       🏫 SCHOOL CLUB MEMBER BADGE")
print("======================================")

name = input("Enter member name: ")
club = input("Enter club name: ")
grade = input("Enter grade: ")
member_id = input("Enter member ID: ")
role = input("Enter club role: ")

print()
print("======================================")
print("          SCHOOL CLUB BADGE")
print("======================================")
print("Name      :", name)
print("Club      :", club)
print("Grade     :", grade)
print("Member ID :", member_id)
print("Role      :", role)
print("======================================")
print("        Welcome to the club! 🎉")
print("======================================")