print("================================")
print("        MY DAILY ROUTINE")
print("================================")

print("6:00 AM - Wake up")
print("6:15 AM - Brush my teeth")
print("6:30 AM - Take a bath")
print("7:00 AM - Have breakfast")
print("7:30 AM - Go to school")
print("8:00 AM - Attend classes")
print("1:00 PM - Have lunch")
print("4:00 PM - Return home")
print("4:30 PM - Take a rest")
print("5:00 PM - Play games")
print("6:00 PM - Study")
print("8:00 PM - Have dinner")
print("9:00 PM - Complete homework")
print("10:00 PM - Go to sleep")

print("================================")
print("        END OF ROUTINE")
print("================================")